<?php
/**
 * Asset Source contract — the swap point between blank and filled packages.
 *
 * Package_Builder and Package_Zip_Writer depend on this interface, never on
 * blank-only logic. MVP ships Blank_Asset_Source (canonical, unmodified
 * assets). A future Filled_Asset_Source implements the same contract to emit
 * filled bytes without changing the manifest, ZIP, or preview layers.
 *
 * Note: the autoloader maps module classes to `class-*.php`, so this interface
 * intentionally lives in class-asset-source.php.
 *
 * @package ProSeCore
 */

namespace ProSe\Core\PackageBuilder;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Interface Asset_Source
 */
interface Asset_Source {

	/**
	 * Resolve a single form record into a manifest form entry.
	 *
	 * @param array<string, mixed> $form_record Canonical form record (or empty when missing).
	 * @param string               $code        Requested form code.
	 * @param string               $stage       Workflow stage label.
	 * @param string               $requirement Requirement level (required|optional).
	 * @return array<string, mixed> Manifest form entry. Includes an `error` key when unresolved.
	 */
	public function resolve( array $form_record, string $code, string $stage, string $requirement ): array;

	/**
	 * Absolute path to the bytes that should be placed into the package for a form.
	 *
	 * For blank packages this is the canonical asset path (copy-only). A filled
	 * source would return a path to generated bytes instead.
	 *
	 * @param array<string, mixed> $form_entry Manifest form entry from resolve().
	 * @return string|null Absolute readable path, or null when unavailable.
	 */
	public function open( array $form_entry ): ?string;
}
